name: Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Get-SourceCode:
    uses: SMTG-04/Reusable/.github/workflows/cloneGitConfigs.yml@main
    with:
      artifact: "ClonedRepo"
    secrets:
      VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
      VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
      GIT_REPO: ${{ secrets.GITLAB_REPOSITORY }}

  Dashboard-CreateProduct:
    needs: Get-SourceCode
    uses: SMTG-04/Reusable/.github/workflows/seleniumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      test_name: "Dashboard-CreateProduct"
      test_config: "test_config/web/createProductTest.xml"
      branch_name: "GoSELL-Thang"

  Dashboard-UpdateProduct:
    needs: Get-SourceCode
    uses: SMTG-04/Reusable/.github/workflows/seleniumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      test_name: "Dashboard-UpdateProduct"
      test_config: "test_config/web/updateProductTest.xml"
      branch_name: "GoSELL-Thang"

  Dashboard-ProductManagement:
    needs:
      - Dashboard-CreateProduct
      - Dashboard-UpdateProduct

    if: always()
    uses: SMTG-04/Reusable/.github/workflows/seleniumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      test_name: "Dashboard-ProductManagement"
      test_config: "test_config/web/productManagementTest.xml"
      branch_name: "GoSELL-Thang"

  Storefront-ProductDetail-NormalxWithoutVariation:
    needs: Get-SourceCode
    uses: SMTG-04/Reusable/.github/workflows/seleniumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      test_name: "Storefront-ProductDetail-NormalxWithoutVariation"
      test_config: "test_config/web/productDetail_Normal_withoutVariation.xml"
      branch_name: "GoSELL-Thang"

  Storefront-ProductDetail-IMEIxWithoutVariation:
    needs: Get-SourceCode
    uses: SMTG-04/Reusable/.github/workflows/seleniumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      test_name: "Storefront-ProductDetail-IMEIxWithoutVariation"
      test_config: "test_config/web/productDetail_IMEI_withoutVariation.xml"
      branch_name: "GoSELL-Thang"

  Storefront-ProductDetail-NormalxVariation:
    needs: Get-SourceCode
    uses: SMTG-04/Reusable/.github/workflows/seleniumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      test_name: "Storefront-ProductDetail-NormalxVariation"
      test_config: "test_config/web/productDetail_Normal_Variation.xml"
      branch_name: "GoSELL-Thang"

  Storefront-ProductDetail-IMEIxVariation:
    needs: Get-SourceCode
    uses: SMTG-04/Reusable/.github/workflows/seleniumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      test_name: "Storefront-ProductDetail-IMEIxVariation"
      test_config: "test_config/web/productDetail_IMEI_Variation.xml"
      branch_name: "GoSELL-Thang"

  Storefront-ProductDetail-Promotion:
    needs:
      - Storefront-ProductDetail-NormalxWithoutVariation
      - Storefront-ProductDetail-IMEIxWithoutVariation
      - Storefront-ProductDetail-NormalxVariation
      - Storefront-ProductDetail-IMEIxVariation

    if: always()
    uses: SMTG-04/Reusable/.github/workflows/seleniumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      test_name: "Storefront-ProductDetail-Promotion"
      test_config: "test_config/web/productDetail_combinePromotion.xml"
      branch_name: "GoSELL-Thang"

  Android-GoSELLER-CreateProduct:
    needs: Get-SourceCode
    uses: SMTG-04/Reusable/.github/workflows/androidAppiumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      appium_port: "4723"
      test_name: "Android-GoSELLER-CreateProduct"
      test_config: "test_config/android/seller/createProductTest.xml"
      branch_name: "GoSELL-Thang"

  Android-GoSELLER-UpdateProduct:
    needs: Get-SourceCode
    uses: SMTG-04/Reusable/.github/workflows/androidAppiumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      appium_port: "4723"
      test_name: "Android-GoSELLER-UpdateProduct"
      test_config: "test_config/android/seller/editProductTest.xml"
      branch_name: "GoSELL-Thang"

  Android-GoSELLER-ProductManagement:
    needs:
      - Android-GoSELLER-CreateProduct
      - Android-GoSELLER-UpdateProduct
    if: always()
    uses: SMTG-04/Reusable/.github/workflows/androidAppiumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      appium_port: "4723"
      test_name: "Android-GoSELLER-ProductManagement"
      test_config: "test_config/android/seller/productManagementTest.xml"
      branch_name: "GoSELL-Thang"

  IOS-GoSELLER-CreateProduct:
    needs: Get-SourceCode
    uses: SMTG-04/Reusable/.github/workflows/iosAppiumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      appium_port: "4723"
      test_name: "IOS-GoSELLER-CreateProduct"
      test_config: "test_config/iOS/seller/createProductTest.xml"
      branch_name: "GoSELL-Thang"

  IOS-GoSELLER-UpdateProduct:
    needs: Get-SourceCode
    if: always()
    uses: SMTG-04/Reusable/.github/workflows/iosAppiumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      appium_port: "4723"
      test_name: "IOS-GoSELLER-UpdateProduct"
      test_config: "test_config/iOS/seller/editProductTest.xml"
      branch_name: "GoSELL-Thang"

  IOS-GoSELLER-ProductManagement:
    needs:
      - IOS-GoSELLER-CreateProduct
      - IOS-GoSELLER-UpdateProduct
    if: always()
    uses: SMTG-04/Reusable/.github/workflows/iosAppiumConfigs.yml@main
    with:
      artifact: "ClonedRepo"
      appium_port: "4723"
      test_name: "IOS-GoSELLER-ProductManagement"
      test_config: "test_config/iOS/seller/productManagementTest.xml"
      branch_name: "GoSELL-Thang"


  CleanJob:
    runs-on: ubuntu-20.04
    needs:
      - Dashboard-ProductManagement
      - Storefront-ProductDetail-Promotion
      - Android-GoSELLER-ProductManagement
      - IOS-GoSELLER-ProductManagement

    if: always()
    steps:
      - name: Delete clone repository
        uses: geekyeggo/delete-artifact@v5
        with:
          name: ClonedRepo

